version: "3"
networks:
  iot:
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - /home/dp/project/mosquitto/config:/mosquitto/config
      - /home/dp/project/mosquitto/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 1883:1883
    restart: unless-stopped
    networks:
      - iot

  nodered:
    image: nodered/node-red
    container_name: nodered
    volumes:
      - /home/dp/project/nodered:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 1880:1880
    restart: unless-stopped
    networks:
      -  iot

  influxdb:
    image: influxdb
    container_name: influxdb
    volumes:
      - /home/dp/project/influxdb:/var/lib/influxdb2
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 8086:8086
    restart: unless-stopped
    networks:
      - iot

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: root
    volumes:
      - /home/dp/project/grafana:/var/lib/grafana
      - /home/dp/project/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - iot

  loki:
    image: grafana/loki
    container_name: loki
    volumes:
      - /home/dp/project/loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 3100:3100
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - iot

  promtail:
    image: grafana/promtail
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /home/dp/project/mosquitto/log/:/var/log/mosquitto/
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /home/dp/project/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - iot
